server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

angular:
  url: 'http://localhost:4200'